name: Build and Release PyPy Sysext

on:
  push:
    tags:
      - 'v*' # Trigger workflow when a tag like v1.0, v20250404 is pushed

jobs:
  build_and_release:
    name: Build PyPy Sysext and Create Release
    runs-on: ubuntu-latest # Use Linux runner for mksquashfs
    permissions:
      contents: write # Needed to create releases/upload assets

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y squashfs-tools curl

      - name: Run build script
        id: build
        run: ./scripts/build-pypy-sysext.sh

      - name: Read build artifacts info
        id: artifacts_info
        run: |
          SYSEXT_FILE=$(find build_sysext -name '*-sysext.raw')
          SHA256_FILE="${SYSEXT_FILE}.sha256"
          HASH=$(cat ${SHA256_FILE})
          echo "sysext_path=${SYSEXT_FILE}" >> $GITHUB_OUTPUT
          echo "sha256_path=${SHA256_FILE}" >> $GITHUB_OUTPUT
          echo "sysext_filename=$(basename ${SYSEXT_FILE})" >> $GITHUB_OUTPUT
          echo "sha256_filename=$(basename ${SHA256_FILE})" >> $GITHUB_OUTPUT
          echo "sysext_sha256=${HASH}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }} # Use the pushed tag name for the release
          name: PyPy Sysext ${{ github.ref_name }}
          body: |
            PyPy Sysext generated by GitHub Actions.
            SHA256: `${{ steps.artifacts_info.outputs.sysext_sha256 }}`
          files: |
            ${{ steps.artifacts_info.outputs.sysext_path }}
            ${{ steps.artifacts_info.outputs.sha256_path }}